version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s

  airflow-webserver:
    build: .  # Esto indica que use el Dockerfile en el directorio actual
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW_CONN_GOOGLE_CLOUD_DEFAULT: >-
        google-cloud-platform://?key_path=/opt/airflow/keys/credenciales.json&project=tu-proyecto-id&scope=https://www.googleapis.com/auth/cloud-platform
      _AIRFLOW_DB_MIGRATE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: airflow
      _AIRFLOW_WWW_USER_PASSWORD: airflow
      _AIRFLOW_WWW_USER_FIRSTNAME: Air
      _AIRFLOW_WWW_USER_LASTNAME: Flow
      _AIRFLOW_WWW_USER_ROLE: Admin
      _AIRFLOW_WWW_USER_EMAIL: admin@example.com
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./gcp_keys/credenciales.json:/opt/airflow/keys/credenciales.json:ro
    ports:
      - "8080:8080"
    command: "airflow standalone"  # Cambié 'webserver' a 'standalone'
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      retries: 5
      start_period: 30s

  airflow-scheduler:
    build: .  # Esto indica que use el Dockerfile en el directorio actual
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW_CONN_GOOGLE_CLOUD_DEFAULT: >-
        google-cloud-platform://?key_path=/opt/airflow/keys/credenciales.json&project=tu-proyecto-id&scope=https://www.googleapis.com/auth/cloud-platform
      BIGQUERY_PROJECT_ID: ${BIGQUERY_PROJECT_ID}
      BIGQUERY_DATASET_ID: ${BIGQUERY_DATASET_ID}
      BIGQUERY_TABLE_ID: ${BIGQUERY_TABLE_ID}
      DATAFORM_PROJECT_ID: ${DATAFORM_PROJECT_ID}
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./gcp_keys/credenciales.json:/opt/airflow/keys/credenciales.json:ro
    command: scheduler
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8974/health"]
      interval: 30s
      retries: 5
      start_period: 30s

  airflow-init:
    build: .  # Esto indica que use el Dockerfile en el directorio actual
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      _AIRFLOW_DB_MIGRATE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: airflow
      _AIRFLOW_WWW_USER_PASSWORD: airflow
      _AIRFLOW_WWW_USER_FIRSTNAME: Air
      _AIRFLOW_WWW_USER_LASTNAME: Flow
      _AIRFLOW_WWW_USER_ROLE: Admin
      _AIRFLOW_WWW_USER_EMAIL: admin@example.com
    command: airflow db migrate
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres-db-volume:
